### ISSUE TITLE
ASK: how to start single window application

### ISSUE THREAD

**Issue by GabrieleRisso** [selkies-project/docker-nvidia-egl-desktop#18]
Hello, I love this repo. thanks so much.

I'm trying to start a single X client instead of the full xfce4-session.  So far I've tried with xstart <cmd> but no result so far. any ideas? 

My end goal is to run: 
startx /usr/bin/qemu-system-x86_64 ...

**Comment by ehfd** [comment]
You should not use startx. Just replace xfce4-session with the program you want to run in entrypoint.sh.

**Comment by ehfd** [comment]
And also, you probably need privileges for qemu. Unprivileged Docker or Kubernetes isn't sufficient for creating a VM.

**Comment by GabrieleRisso** [comment]
Thanks so much, It definitely works adding - - device=/dev/kvm and network host. I still can't make it work with my AMD gpu

**Comment by ehfd** [comment]
Hi, an AMD GPU is possible, you have to pass /dev/dri in that case and install missing drivers inside the container. Please do tell me what you installed.

**Comment by GabrieleRisso** [comment]
Thanks for the quick replay, I'm on it.

**Comment by ehfd** [comment]
Pleasse leave a message if you need more help.
I have also installed AMD/Intel drivers.
