### ISSUE TITLE
Will this work without i386 ?

### ISSUE THREAD

**Issue by elgalu** [selkies-project/docker-nvidia-egl-desktop#24]
I was wondering if I remove all i386 references and try to use only amd64 architecture, will this project still work? or does it really need all the i386 packages?

**Comment by ehfd** [comment]
i386 is mostly for Wine and virtualgl32 (and the NVIDIA x86 driver components in case of glx desktop).
Not much issues if you don't run anything 32 bit and remove the above mentioned components.
