### ISSUE TITLE
SIGKILL/SIGSTOP can not be trapped

### ISSUE THREAD

**Issue by elgalu** [selkies-project/docker-nvidia-egl-desktop#25]
https://github.com/selkies-project/docker-nvidia-egl-desktop/blob/f79e995fba666c5431893c768d786d52621a89ab/entrypoint.sh#L7

SIGKILL/SIGSTOP can not be trapped.shellcheck

https://www.shellcheck.net/wiki/SC2173

**Comment by ehfd** [comment]
Understood. Will fix in some time.

**Comment by ehfd** [comment]
Completed.
