### ISSUE TITLE
Missing gstreamer plugins nice, webrtc, dtls, ...

### ISSUE THREAD

**Issue by elgalu** [selkies-project/docker-nvidia-egl-desktop#26]
Hi, thanks a lot for this repo, it's been extremely useful!

I've customized the container considerable and for some reason I get an error after running `selkies-gstreamer --addr="127.0.0.1" --port="8080"`

```sh
Traceback (most recent call last):
  File "/opt/conda/bin/selkies-gstreamer", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/selkies_gstreamer/__main__.py", line 527, in main
    app = GSTWebRTCApp(stun_servers, turn_servers, enable_audio, audio_channels, curr_fps, args.encoder, curr_video_bitrate, curr_audio_bitrate)
  File "/opt/conda/lib/python3.10/site-packages/selkies_gstreamer/gstwebrtc_app.py", line 83, in __init__
    self.check_plugins()
  File "/opt/conda/lib/python3.10/site-packages/selkies_gstreamer/gstwebrtc_app.py", line 654, in check_plugins
    raise GSTWebRTCAppError('Missing gstreamer plugins:', missing)
gstwebrtc_app.GSTWebRTCAppError: ('Missing gstreamer plugins:', ['nice', 'webrtc', 'dtls', 'srtp', 'rtp', 'sctp', 'rtpmanager', 'ximagesrc', 'nvcodec'])
```

The plugins seem to be there, any tip on what to look at I would appreciate.

```sh
ll /opt/gstreamer/lib/x86_64-linux-gnu/libgstwebrtc-1.0.so
ll /opt/gstreamer/lib/x86_64-linux-gnu/libgstwebrtc-1.0.so.0
ll /opt/gstreamer/lib/x86_64-linux-gnu/libgstwebrtc-1.0.so.0.2005.0
etc...
```

**Comment by ehfd** [comment]
@danisla any clues?

**Comment by elgalu** [comment]
Perhaps related:

```
WARNING:root:Namespace(json_config='/tmp/selkies_config.json', addr='127.0.0.1', port='8080', enable_basic_auth='true',
basic_auth_user='lgallucci', basic_auth_password='****', web_root='/opt/gst-web', coturn_web_uri='',
coturn_web_username='selkies-0b71d3bd1522', coturn_auth_header_name='x-auth-user', rtc_config_json='/tmp/rtc.json',
turn_shared_secret='', turn_username='', turn_password='', turn_host='', turn_port='', turn_protocol='udp',
turn_tls='false', uinput_mouse_socket='', uinput_js_socket='', enable_audio='true', audio_channels='2',
enable_clipboard='true', app_auto_init='true', app_ready_file='/var/run/appconfig/appready', framerate='30',
video_bitrate='2000', audio_bitrate='64000', encoder='nvh264enc', enable_resize='false', enable_cursors='true',
debug_cursors='false', cursor_size='24', metrics_port='8000', debug=False)
```

**Comment by ehfd** [comment]
@elgalu Need all the logs. And which GStreamer did you use?

**Comment by ehfd** [comment]
@elgalu Oh, and thank you for the sponsorship. I am quite busy so the repository is in maintenance mode so I regret not being able to be more active but I really appreciate it.

**Comment by ehfd** [comment]
Just to confirm, did you install all the apt dependencies?

**Comment by ehfd** [comment]
> Yes, all apt dependencies are installed. GStreamer: SELKIES_VERSION="1.3.7". Perhaps the introduction of conda messed up the plugins search paths. We'll use xpra for now. I'll re-open if I can create a reproducible public container some day. Thanks!

Ah, wait. Conda. You need to install all the dependencies in Conda.

**Comment by ehfd** [comment]
Search in conda-forge all the dependencies including Cuda and install everything.

**Comment by elgalu** [comment]
Cool! so I installed a few `gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly gst-python gst-libav webrtcvad` and now the list of missing plugins is reduced to 3: `'Missing gstreamer plugins:', ['nice', 'webrtc', 'srtp']`

**Comment by ehfd** [comment]
`sudo apt-get update && sudo apt-get install --no-install-recommends -y adwaita-icon-theme-full build-essential python3-pip python3-dev python3-gi python3-setuptools python3-wheel tzdata sudo udev xclip x11-utils xdotool wmctrl jq gdebi-core x11-xserver-utils xserver-xorg-core libopus0 libgdk-pixbuf2.0-0 libsrtp2-1 libxdamage1 libxml2-dev libwebrtc-audio-processing1 libcairo-gobject2 pulseaudio libpulse0 libpangocairo-1.0-0 libgirepository1.0-dev libjpeg-dev libvpx-dev zlib1g-dev x264`

This was the long list of dependencies, where I believe you might want to find or build `'nice', 'webrtc', 'srtp'` manually on Conda.

I think: `pylibsrtp` provides `srtp`. 

https://webrtc.googlesource.com/src
https://gitlab.freedesktop.org/libnice/libnice

https://developer.ridgerun.com/wiki/index.php/GStreamer_WebRTC_Wrapper/Getting_the_Code/Building_and_Installation_Guide
https://gitlab.freedesktop.org/libnice/libnice/-/issues/112
https://webrtcmagazine.wordpress.com/tag/libnice/

This is pretty much uncharted territory, and I would really appreciate if you could test things. You could ask on `#gstreamer` at oftc.org IRC or `#_oftc_#gstreamer:matrix.org` on Matrix for help from GStreamer devs.

Discussion continues on #63.

**Comment by ehfd** [comment]
@elgalu Very late, but a portable distribution is now ready, based on Conda (still can't `conda install -c conda-forge selkies-gstreamer` but the CI builds them for you).

**Comment by elgalu** [comment]
thanks!! highly apprecianted<3
