### ISSUE TITLE
The screen locker is broken and unlocking is not possible anymore

### ISSUE THREAD

**Issue by elgalu** [selkies-project/docker-nvidia-egl-desktop#28]
When using `NOVNC_ENABLE=true` we get the screen locked after some time showing a black screen with `The screen locker is broken and unlocking is not possible anymore` does anyone knows how to get passed this?
![image](https://github.com/selkies-project/selkies-gstreamer/assets/111569/9eaa0785-a89a-481f-a1a1-49a84200f187)

Using: `ghcr.io/selkies-project/nvidia-egl-desktop:latest`

**Comment by ehfd** [comment]
I was going to remove the locker altogether. In the backlogs.

**Comment by elgalu** [comment]
cool! do you know how can we remove it manually for now?

**Comment by ehfd** [comment]
https://www.simplified.guide/kde/lock-screen-configure
For now.

**Comment by elgalu** [comment]
ok I was able to restore it via the command line and without rebooting:

```sh
kwriteconfig5 --file ~/.config/kscreenlockerrc --group Daemon --key Autolock false
killall ksmserver plasmashell
```

**Comment by ehfd** [comment]
We need something like this to configure globally in the system directories: https://www.reddit.com/r/kde/comments/r4yey1/systemwide_config_for_all_users/hmkz0g0/

**Comment by ehfd** [comment]
> Or, one other option is to (somehow) safely remove kscreenlocker without touching anything else.

This is not possible. Global configuration is required.

**Comment by ehfd** [comment]
@elgalu 

Could you do me a favor and see if copying the contents of your `~/.config/kscreenlockerrc` to `/usr/share/kubuntu-default-settings/kf5-settings/kscreenlockerrc` then removing `~/.config/kscreenlockerrc` works for you?

**Comment by ehfd** [comment]
https://develop.kde.org/docs/administration/kiosk/introduction/#kde-action-restrictions

```
[KDE Action Restrictions][$i]
lock_screen=false
```

in `/etc/xdg/kdeglobals` might work systemwide. Not sure.

**Comment by ehfd** [comment]
https://github.com/selkies-project/docker-nvidia-egl-desktop/commit/a11e1581eb6de406d05324267db62782fd67fafe

I think this commit works. @elgalu Please close if it does and tag me if it doesn't.

**Comment by ehfd** [comment]
It should work. Please reopen if there are any issues.
