### ISSUE TITLE
selkies will not connect to the TURN forwarding port even if a coturn ip is set in the environment 

### ISSUE THREAD

**Issue by ghost** [selkies-project/docker-nvidia-egl-desktop#30]
selkies will not connect to the TURN forwarding port even if a coturn is set in the environment. 

it will only use the coturn as a STUN server and get the container's ip address, which in my case is behind the firewall.

**Comment by ehfd** [comment]
First thing up my mind: you must expose the relay ports that you have set in the coturn configuration.

**Comment by ehfd** [comment]
Ah. I see the issue.

One problem is, you are using an internal IP. That IP is used both for the client and the host. If any if the two is outside that internal network, no way it's going to find the TURN server. It should (somehow) resolve differently to work.

**Comment by ehfd** [comment]
I think there was a setting in coturn to choose which IP to bind to, if so.

**Comment by ehfd** [comment]
There is a "Force relay connection" option in the web ui.

**Comment by ehfd** [comment]
@xhejtman
I think we discussed a similar issue around 8 months ago?

**Comment by xhejtman** [comment]
> @xhejtman I think we discussed a similar issue around 8 months ago?

I do not think so. However, @nick008a, would you be able to split networks with turn and selkies to be different? Like add another network for coturn and use it? Maybe there is some heuristics that thinks that selkies is directly connected. Btw, any chance to run browser on the node that runs coturn to check, if it works from the same host?

**Comment by ehfd** [comment]
@nick008a I believe you could ask the folks at https://github.com/coturn/coturn.

A trick I can tell you is that [`--rtc_config_json`](https://github.com/selkies-project/selkies-gstreamer/blob/70b231e26652b4069c85d07656b3f9fb574631ea/src/selkies_gstreamer/__main__.py#L329) is the WebRTC configuration used for the client, while the `--turn_host` is used for the server. It's possible to use different hosts for the web client and the server.
