### ISSUE TITLE
replace noVNC to KasmVNC

### ISSUE THREAD

**Issue by ghost** [selkies-project/docker-nvidia-egl-desktop#32]
kasmVNC has better support for clipborad, sound, remote files, compared to noVNC. 

https://github.com/kasmtech/KasmVNC.git

**Comment by ehfd** [comment]
I will work on it. Eyeing the right time but until 1.1.0 some small issues ultimately broke KasmVNC in my container. May have changed in 1.2.0.

**Comment by ehfd** [comment]
I am not basing on a custom container because I can't handle upstream issues. It can be installed, just some rigor in testing is needed.

**Comment by ehfd** [comment]
Next in priority.

**Comment by ehfd** [comment]
KasmVNC seems nicer because it now supports multithreaded encoding. It used to lack performance to x11vnc because of this reason.

**Comment by read8873** [comment]
any chance this gets supported?

**Comment by ehfd** [comment]
Soon.

**Comment by ehfd** [comment]
Completed. There is https://github.com/linuxserver/kclient for audio but it's far too much work that isn't even documented. I'll accept contributions, though.

**Comment by ehfd** [comment]
@write3371 
Moonlight won't work with Kubernetes at all. And it needs to expose a lot of ports.

**Comment by ehfd** [comment]
None of this going to work with Kubernetes. Selkies-GStreamer was meant to work in Kubernetes AND deliver similar performance to GoW or Wolf or Sunshine.

**Comment by ehfd** [comment]
> Completed. There is https://github.com/linuxserver/kclient for audio but it's far too much work that isn't even documented. I'll accept contributions, though.

If someone is interested, you could pay one of our contributors (@danisla, @ayunami2000, @PMohanJ, etc.) to implement this, and I'll review it.

**Comment by ehfd** [comment]
No vibration, but yes for the gamepad itself. It's been a long time since anyone tested it, though and I'm not sure how it will work.
@write3371

**Comment by ehfd** [comment]
I don't have a gamepad right now, so let's first upload the `/tmp/*.log` files first.

**Comment by ehfd** [comment]
@write3371 Turns out I did something stupid with the permissions with `/dev/input/js*`. Please tell me how the new build works.
