### ISSUE TITLE
Configure a fixed UDP port instead of using turn

### ISSUE THREAD

**Issue by read8873** [selkies-project/docker-nvidia-egl-desktop#36]
I am trying selkies in an internal network where it's hard to reach external turn servers. 

Is it possible to override the UDP port that selkies listens and also the final UDP end point (container1.server1.lan:12345) that will be send to the web browser for RTC?

**Comment by ehfd** [comment]
Other WebRTC libraries (such as Pion) have support for it, but not GStreamer as of currently.

However, why not try a single relay port TURN server in the internal network if that's the concern?

**Comment by ehfd** [comment]
I recommend using coTURN with `max-port` and `min-port` for now.

Check: https://github.com/selkies-project/selkies-gstreamer/blob/main/docs/component.md#coturn

**Comment by ehfd** [comment]
Implemented in https://github.com/selkies-project/docker-nvidia-egl-desktop/commit/9a1d3e239d95b1f55fd24947d60b4fce397f5b6f
