### ISSUE TITLE
fakeroot fails during build process

### ISSUE THREAD

**Issue by alexeadem** [selkies-project/docker-nvidia-egl-desktop#40]
Docker version 24.0.5, build %{shortcommit_cli}

```
#12 183.9 dpkg: error processing archive /tmp/apt-dpkg-install-bVaKXy/133-alsa-base_1.0.25+dfsg-0ubuntu7_all.deb (--unpack):
#12 183.9  error creating directory './sbin': Permission denied
```

**Comment by ehfd** [comment]
Under investigation.

**Comment by ehfd** [comment]
Possibly have been fixed. Please check on all Ubuntu versions.

**Comment by ehfd** [comment]
I checked all Ubuntu versions on Docker 27.1.0. Please reopen if there are problems.

**Comment by ehfd** [comment]
Also tested on Kaniko, which works on much restrictive conditions compared to docker build.

**Comment by alexeadem** [comment]
docker build works now after the changes. Thank you! You may want to do the same for egl.
