### ISSUE TITLE
substitution fails ind dockerfile 

### ISSUE THREAD

**Issue by alexeadem** [selkies-project/docker-nvidia-egl-desktop#41]
```
# dbus-daemon to the below address is required during startup
ENV DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR:-/tmp}/dbus-session-${DISPLAY#*:}"
```
```
error: failed to solve: rpc error: code = Unknown desc = failed to process "\"unix:path=${XDG_RUNTIME_DIR:-/tmp}/dbus-session-${DISPLAY#*:}\"": missing ':' in substitution
````

docker version
Client:
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.22.0
 Git commit:        %{shortcommit_cli}
 Built:             Sun Feb 11 23:35:47 2024
 OS/Arch:           linux/amd64
 Context:           default

**Comment by alexeadem** [comment]
I think I'm getting these errors cause your are building with GitHub Actions and I'm trying to build it locally...

**Comment by ehfd** [comment]
Fixed by replacing `dbus-session-${DISPLAY#*:}` with `dbus-session-bus`.
