### ISSUE TITLE
Hello please help me i am need execute python pyodbc for a sql server connection and i am getting always segmentation fault anyone help me for fix this

### ISSUE THREAD

**Issue by kbond2024** [selkies-project/docker-nvidia-egl-desktop#43]
Hello please help me i am need execute python pyodbc for a sql server connection and i am getting always segmentation fault anyone help me for fix this

**Comment by PMohanJ** [comment]
I don't think this is anything relevant to selkies-project. But if it does, please elaborate it more.

**Comment by dimm0** [comment]
+1
Not relevant here, but at least post a minimal reproducible example

**Comment by ehfd** [comment]
I think it's about the containerization rather than the desktop. There should be some information for your workload about containers.

**Comment by ehfd** [comment]
Should be redirected to https://github.com/mkleehammer/pyodbc.
